#!/bin/bash

BLOCK_DEVICE=/dev/sr0
ROLL_NUMBER=$1
PICTURE_DATE=$2

#clear workspace
rm -f ~/tmp/conversions/*

#Copy images from disk
udisksctl mount -b $BLOCK_DEVICE
let i=0
for x in /media/dean/$ROLL_NUMBER/$ROLL_NUMBER.rol/*
do
    let i++
    cp $x ~/tmp/conversions/"_image_$(printf '%02d' "${i}")".sfw
done
udisksctl unmount -b $BLOCK_DEVICE

#convert images
for p in ~/tmp/conversions/*
do
    sfwjpg $p 
done

rm -f ~/tmp/conversions/*.sfw

for x in ~/tmp/conversions/*
do
    jpegtran -flip vertical $x > ~/tmp/final/$PICTURE_DATE$(basename $x)
done

echo Complete
